pybot --outputdir .\Report\ -T ^
TC_Base\PrepareMachineA.robot ^
TC_Set\SetOption.robot ^
TC_Set\SetExternaCardReaderTable.robot ^
TC_Set\SetSolutionsApplication.robot ^
TC_Set\SetScanFileNameTable.robot ^
TC_Set\SetProfileFTP.robot ^
TC_Set\SetProfileSFTP.robot ^
TC_Set\SetProfileNetwork.robot ^
TC_Set\SetProfileSharePoint.robot ^
TC_Set\SetProfileHTTP(S)Option.robot ^
TC_Set\SetProfileHTTP(S).robot ^
TC_Set\SetSecureFunctionLock.robot ^
TC_Set\SetSecureFunctionLockUserListTable.robot ^
TC_Set\SetAddressBook.robot ^
TC_Base\DeployExIm.robot ^
TC_Base\PrepareMachineB.robot ^
TC_Get\GetOption.robot ^
TC_Get\GetExternaCardReaderTable.robot ^
TC_Get\GetSolutionsApplication.robot ^
TC_Get\GetScanFileNameTable.robot ^
TC_Get\GetProfileFTP.robot ^
TC_Get\GetProfileSFTP.robot ^
TC_Get\GetProfileNetwork.robot ^
TC_Get\GetProfileSharePoint.robot ^
TC_Get\GetProfileHTTP(S)Option.robot ^
TC_Get\GetProfileHTTP(S).robot ^
TC_Get\GetSecureFunctionLock.robot ^
TC_Get\GetSecureFunctionLockUserListTable.robot ^
TC_Get\GetAddressBook.robot ^
TC_Base\PrepareMachineA.robot ^
TC_Set\SetAddressBookGroup.robot ^
TC_Base\DeployExIm.robot ^
TC_Base\PrepareMachineB.robot ^
TC_Get\GetAddressBookGroup.robot
